AVR_TOOLS_PATH = /usr/bin
ARDUINO_DIR  = /opt/arduino
TARGET       = base_controller
ARDUINO_LIBS = Servo PID_v1 SoftwareSerial
MCU          = atmega328p
F_CPU        = 16000000

# Upload options for Arduino Uno
ARDUINO_PORT = /dev/ttyACM0
AVRDUDE_CONF = /etc/avrdude.conf
AVRDUDE_ARD_BAUDRATE = 115200
AVRDUDE_ARD_PROGRAMMER = arduino

include ../Arduino.mk
