AVR_TOOLS_PATH = /usr/bin
ARDUINO_DIR  = /opt/arduino
TARGET       = base_controller
ARDUINO_LIBS = Servo SoftwareSerial
MCU          = atmega2560
F_CPU        = 16000000

# Upload options for Arduino Mega 2560
# (use arduino instead of stk500v2 for Arduino Uno)
ARDUINO_PORT = /dev/ttyACM0
AVRDUDE_CONF = /etc/avrdude.conf
AVRDUDE_ARD_BAUDRATE = 115200
AVRDUDE_ARD_PROGRAMMER = stk500v2

include ../Arduino.mk
