ARDUINO_DIR = /home/john/arduino-0021
AVR_TOOLS_PATH = /usr/bin

TARGET       = controller
MCU          = atmega328p
F_CPU        = 16000000
ARDUINO_PORT = /dev/ttyUSB0

ARDUINO_LIBS = AFMotor Servo

include /home/john/arduino-0021/Arduino.mk